name: app
description: Meli Bees App for Android
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  camera: 0.10.5+4
  carousel_slider: 4.2.1
  convert: 3.1.1
  device_info_plus: 9.1.0
  file_picker: 8.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_scroll_shadow: 1.2.4
  geolocator: 11.0.0
  go_router: 14.0.2
  gql: 1.0.1-alpha+1709845491443
  graphql: 5.2.0-beta.7
  graphql_flutter: 5.2.0-beta.6
  http: 1.2.1
  image_picker: 1.0.4
  intl: 0.19.0
  mime: 1.0.4
  p2panda: 0.1.0
  p2panda_flutter: 0.1.0
  path: 1.9.0
  path_provider: 2.1.3
  shared_preferences: 2.2.2
  sliver_tools: 0.2.12
  toml: 0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_native_splash: 2.4.0

flutter:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
  uses-material-design: true

  # Enable code generation for localization
  generate: true

# Run "dart run flutter_native_splash:create" in "app" folder after applying changes here
flutter_native_splash:
  color: "#eaddff"
  android_12:
    color: "#eaddff"