name: app
description: Meli Bees App for Android
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  camera: 0.11.0+1
  carousel_slider: 4.2.1
  convert: 3.1.1
  device_info_plus: 10.1.0
  easy_image_viewer: 1.5.0
  file_picker: 8.0.3
  flutter:
    sdk: flutter
  flutter_image_compress: 2.3.0
  flutter_localizations:
    sdk: flutter
  flutter_scroll_shadow: 1.2.4
  geolocator: 12.0.0
  go_router: 14.1.4
  gql: 1.0.1-alpha+1709845491443
  graphql: 5.2.0-beta.7
  graphql_flutter: 5.2.0-beta.6
  http: 1.2.1
  image_picker: 1.1.2
  intl: 0.19.0
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: 0.18.0
  mime: 1.0.5
  p2panda: 0.1.1
  p2panda_flutter: 0.1.1
  package_info_plus: 8.0.0
  path: 1.9.0
  path_provider: 2.1.3
  shared_preferences: 2.2.3
  sliver_tools: 0.2.12
  toml: 0.15.0
  uuid: 4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_native_splash: 2.4.0

flutter:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
  uses-material-design: true

  # Enable code generation for localization
  generate: true

# Run "dart run flutter_native_splash:create" in "app" folder after applying changes here
flutter_native_splash:
  color: "#eaddff"
  android_12:
    color: "#eaddff"
