name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          channel: "1.74"
          components: rustfmt
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # AdoptOpenJDK is now Eclipse Temurin
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"
      - uses: bluefireteam/melos-action@v3
      - name: Install Dart dependencies
        run: dart pub get
      - name: Generate FFI bindings and build native Android libraries
        run: melos build
      - name: Build APK
        working-directory: ./packages/app
        run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: packages/app/build/app/outputs/flutter-apk/app-release.apk
